/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersIndexRouteImport } from './routes/users/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as ChatIndexRouteImport } from './routes/chat/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as AgentsIndexRouteImport } from './routes/agents/index'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as DocsIdIndexRouteImport } from './routes/docs/$id/index'
import { Route as BlogIdIndexRouteImport } from './routes/blog/$id/index'
import { Route as ApiZeroclawIndexRouteImport } from './routes/api/zeroclaw/index'
import { Route as ApiAgentsIndexRouteImport } from './routes/api/agents/index'
import { Route as ApiAgentSessionsIndexRouteImport } from './routes/api/agent-sessions/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAgentsEnabledRouteImport } from './routes/api/agents/enabled'
import { Route as ApiUsersMeIndexRouteImport } from './routes/api/users/me/index'
import { Route as ApiAgentsAgentIdIndexRouteImport } from './routes/api/agents/$agentId/index'
import { Route as ApiAgentSessionsSessionIdIndexRouteImport } from './routes/api/agent-sessions/$sessionId/index'
import { Route as ApiAgentSessionsSessionIdWsRouteImport } from './routes/api/agent-sessions/$sessionId/ws'
import { Route as ApiAgentSessionsSessionIdMessagesIndexRouteImport } from './routes/api/agent-sessions/$sessionId/messages/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIndexRoute = AgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIdIndexRoute = DocsIdIndexRouteImport.update({
  id: '/docs/$id/',
  path: '/docs/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIdIndexRoute = BlogIdIndexRouteImport.update({
  id: '/blog/$id/',
  path: '/blog/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiZeroclawIndexRoute = ApiZeroclawIndexRouteImport.update({
  id: '/api/zeroclaw/',
  path: '/api/zeroclaw/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentsIndexRoute = ApiAgentsIndexRouteImport.update({
  id: '/api/agents/',
  path: '/api/agents/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentSessionsIndexRoute = ApiAgentSessionsIndexRouteImport.update({
  id: '/api/agent-sessions/',
  path: '/api/agent-sessions/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentsEnabledRoute = ApiAgentsEnabledRouteImport.update({
  id: '/api/agents/enabled',
  path: '/api/agents/enabled',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersMeIndexRoute = ApiUsersMeIndexRouteImport.update({
  id: '/api/users/me/',
  path: '/api/users/me/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentsAgentIdIndexRoute = ApiAgentsAgentIdIndexRouteImport.update({
  id: '/api/agents/$agentId/',
  path: '/api/agents/$agentId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentSessionsSessionIdIndexRoute =
  ApiAgentSessionsSessionIdIndexRouteImport.update({
    id: '/api/agent-sessions/$sessionId/',
    path: '/api/agent-sessions/$sessionId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAgentSessionsSessionIdWsRoute =
  ApiAgentSessionsSessionIdWsRouteImport.update({
    id: '/api/agent-sessions/$sessionId/ws',
    path: '/api/agent-sessions/$sessionId/ws',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAgentSessionsSessionIdMessagesIndexRoute =
  ApiAgentSessionsSessionIdMessagesIndexRouteImport.update({
    id: '/api/agent-sessions/$sessionId/messages/',
    path: '/api/agent-sessions/$sessionId/messages/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/agents/': typeof AgentsIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/chat/': typeof ChatIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/users/': typeof UsersIndexRoute
  '/api/agents/enabled': typeof ApiAgentsEnabledRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/agent-sessions/': typeof ApiAgentSessionsIndexRoute
  '/api/agents/': typeof ApiAgentsIndexRoute
  '/api/zeroclaw/': typeof ApiZeroclawIndexRoute
  '/blog/$id/': typeof BlogIdIndexRoute
  '/docs/$id/': typeof DocsIdIndexRoute
  '/api/agent-sessions/$sessionId/ws': typeof ApiAgentSessionsSessionIdWsRoute
  '/api/agent-sessions/$sessionId/': typeof ApiAgentSessionsSessionIdIndexRoute
  '/api/agents/$agentId/': typeof ApiAgentsAgentIdIndexRoute
  '/api/users/me/': typeof ApiUsersMeIndexRoute
  '/api/agent-sessions/$sessionId/messages/': typeof ApiAgentSessionsSessionIdMessagesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/agents': typeof AgentsIndexRoute
  '/blog': typeof BlogIndexRoute
  '/chat': typeof ChatIndexRoute
  '/docs': typeof DocsIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/users': typeof UsersIndexRoute
  '/api/agents/enabled': typeof ApiAgentsEnabledRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/agent-sessions': typeof ApiAgentSessionsIndexRoute
  '/api/agents': typeof ApiAgentsIndexRoute
  '/api/zeroclaw': typeof ApiZeroclawIndexRoute
  '/blog/$id': typeof BlogIdIndexRoute
  '/docs/$id': typeof DocsIdIndexRoute
  '/api/agent-sessions/$sessionId/ws': typeof ApiAgentSessionsSessionIdWsRoute
  '/api/agent-sessions/$sessionId': typeof ApiAgentSessionsSessionIdIndexRoute
  '/api/agents/$agentId': typeof ApiAgentsAgentIdIndexRoute
  '/api/users/me': typeof ApiUsersMeIndexRoute
  '/api/agent-sessions/$sessionId/messages': typeof ApiAgentSessionsSessionIdMessagesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/agents/': typeof AgentsIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/chat/': typeof ChatIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/users/': typeof UsersIndexRoute
  '/api/agents/enabled': typeof ApiAgentsEnabledRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/agent-sessions/': typeof ApiAgentSessionsIndexRoute
  '/api/agents/': typeof ApiAgentsIndexRoute
  '/api/zeroclaw/': typeof ApiZeroclawIndexRoute
  '/blog/$id/': typeof BlogIdIndexRoute
  '/docs/$id/': typeof DocsIdIndexRoute
  '/api/agent-sessions/$sessionId/ws': typeof ApiAgentSessionsSessionIdWsRoute
  '/api/agent-sessions/$sessionId/': typeof ApiAgentSessionsSessionIdIndexRoute
  '/api/agents/$agentId/': typeof ApiAgentsAgentIdIndexRoute
  '/api/users/me/': typeof ApiUsersMeIndexRoute
  '/api/agent-sessions/$sessionId/messages/': typeof ApiAgentSessionsSessionIdMessagesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/login'
    | '/auth/register'
    | '/agents/'
    | '/blog/'
    | '/chat/'
    | '/docs/'
    | '/profile/'
    | '/users/'
    | '/api/agents/enabled'
    | '/api/auth/$'
    | '/api/agent-sessions/'
    | '/api/agents/'
    | '/api/zeroclaw/'
    | '/blog/$id/'
    | '/docs/$id/'
    | '/api/agent-sessions/$sessionId/ws'
    | '/api/agent-sessions/$sessionId/'
    | '/api/agents/$agentId/'
    | '/api/users/me/'
    | '/api/agent-sessions/$sessionId/messages/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/login'
    | '/auth/register'
    | '/agents'
    | '/blog'
    | '/chat'
    | '/docs'
    | '/profile'
    | '/users'
    | '/api/agents/enabled'
    | '/api/auth/$'
    | '/api/agent-sessions'
    | '/api/agents'
    | '/api/zeroclaw'
    | '/blog/$id'
    | '/docs/$id'
    | '/api/agent-sessions/$sessionId/ws'
    | '/api/agent-sessions/$sessionId'
    | '/api/agents/$agentId'
    | '/api/users/me'
    | '/api/agent-sessions/$sessionId/messages'
  id:
    | '__root__'
    | '/'
    | '/auth/login'
    | '/auth/register'
    | '/agents/'
    | '/blog/'
    | '/chat/'
    | '/docs/'
    | '/profile/'
    | '/users/'
    | '/api/agents/enabled'
    | '/api/auth/$'
    | '/api/agent-sessions/'
    | '/api/agents/'
    | '/api/zeroclaw/'
    | '/blog/$id/'
    | '/docs/$id/'
    | '/api/agent-sessions/$sessionId/ws'
    | '/api/agent-sessions/$sessionId/'
    | '/api/agents/$agentId/'
    | '/api/users/me/'
    | '/api/agent-sessions/$sessionId/messages/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AgentsIndexRoute: typeof AgentsIndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ChatIndexRoute: typeof ChatIndexRoute
  DocsIndexRoute: typeof DocsIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  UsersIndexRoute: typeof UsersIndexRoute
  ApiAgentsEnabledRoute: typeof ApiAgentsEnabledRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiAgentSessionsIndexRoute: typeof ApiAgentSessionsIndexRoute
  ApiAgentsIndexRoute: typeof ApiAgentsIndexRoute
  ApiZeroclawIndexRoute: typeof ApiZeroclawIndexRoute
  BlogIdIndexRoute: typeof BlogIdIndexRoute
  DocsIdIndexRoute: typeof DocsIdIndexRoute
  ApiAgentSessionsSessionIdWsRoute: typeof ApiAgentSessionsSessionIdWsRoute
  ApiAgentSessionsSessionIdIndexRoute: typeof ApiAgentSessionsSessionIdIndexRoute
  ApiAgentsAgentIdIndexRoute: typeof ApiAgentsAgentIdIndexRoute
  ApiUsersMeIndexRoute: typeof ApiUsersMeIndexRoute
  ApiAgentSessionsSessionIdMessagesIndexRoute: typeof ApiAgentSessionsSessionIdMessagesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/': {
      id: '/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/': {
      id: '/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AgentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$id/': {
      id: '/docs/$id/'
      path: '/docs/$id'
      fullPath: '/docs/$id/'
      preLoaderRoute: typeof DocsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$id/': {
      id: '/blog/$id/'
      path: '/blog/$id'
      fullPath: '/blog/$id/'
      preLoaderRoute: typeof BlogIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/zeroclaw/': {
      id: '/api/zeroclaw/'
      path: '/api/zeroclaw'
      fullPath: '/api/zeroclaw/'
      preLoaderRoute: typeof ApiZeroclawIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agents/': {
      id: '/api/agents/'
      path: '/api/agents'
      fullPath: '/api/agents/'
      preLoaderRoute: typeof ApiAgentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent-sessions/': {
      id: '/api/agent-sessions/'
      path: '/api/agent-sessions'
      fullPath: '/api/agent-sessions/'
      preLoaderRoute: typeof ApiAgentSessionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agents/enabled': {
      id: '/api/agents/enabled'
      path: '/api/agents/enabled'
      fullPath: '/api/agents/enabled'
      preLoaderRoute: typeof ApiAgentsEnabledRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users/me/': {
      id: '/api/users/me/'
      path: '/api/users/me'
      fullPath: '/api/users/me/'
      preLoaderRoute: typeof ApiUsersMeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agents/$agentId/': {
      id: '/api/agents/$agentId/'
      path: '/api/agents/$agentId'
      fullPath: '/api/agents/$agentId/'
      preLoaderRoute: typeof ApiAgentsAgentIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent-sessions/$sessionId/': {
      id: '/api/agent-sessions/$sessionId/'
      path: '/api/agent-sessions/$sessionId'
      fullPath: '/api/agent-sessions/$sessionId/'
      preLoaderRoute: typeof ApiAgentSessionsSessionIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent-sessions/$sessionId/ws': {
      id: '/api/agent-sessions/$sessionId/ws'
      path: '/api/agent-sessions/$sessionId/ws'
      fullPath: '/api/agent-sessions/$sessionId/ws'
      preLoaderRoute: typeof ApiAgentSessionsSessionIdWsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent-sessions/$sessionId/messages/': {
      id: '/api/agent-sessions/$sessionId/messages/'
      path: '/api/agent-sessions/$sessionId/messages'
      fullPath: '/api/agent-sessions/$sessionId/messages/'
      preLoaderRoute: typeof ApiAgentSessionsSessionIdMessagesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AgentsIndexRoute: AgentsIndexRoute,
  BlogIndexRoute: BlogIndexRoute,
  ChatIndexRoute: ChatIndexRoute,
  DocsIndexRoute: DocsIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  UsersIndexRoute: UsersIndexRoute,
  ApiAgentsEnabledRoute: ApiAgentsEnabledRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiAgentSessionsIndexRoute: ApiAgentSessionsIndexRoute,
  ApiAgentsIndexRoute: ApiAgentsIndexRoute,
  ApiZeroclawIndexRoute: ApiZeroclawIndexRoute,
  BlogIdIndexRoute: BlogIdIndexRoute,
  DocsIdIndexRoute: DocsIdIndexRoute,
  ApiAgentSessionsSessionIdWsRoute: ApiAgentSessionsSessionIdWsRoute,
  ApiAgentSessionsSessionIdIndexRoute: ApiAgentSessionsSessionIdIndexRoute,
  ApiAgentsAgentIdIndexRoute: ApiAgentsAgentIdIndexRoute,
  ApiUsersMeIndexRoute: ApiUsersMeIndexRoute,
  ApiAgentSessionsSessionIdMessagesIndexRoute:
    ApiAgentSessionsSessionIdMessagesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
